package io.gomint.proxy.inventory;

import lombok.Getter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * @author geNAZt
 * @version 1.0
 */
public enum MaterialMagicNumbers {

    // CHECKSTYLE:OFF
    AIR( 0, "minecraft:air" ),
    STONE( 1, "minecraft:stone" ),
    GRASS_BLOCK( 2, "minecraft:grass_block" ),
    DIRT( 3, "minecraft:dirt" ),
    COBBLESTONE( 4, "minecraft:cobblestone" ),
    WOOD_PLANKS( 5, "minecraft:wood_planks" ),
    SAPLING( 6, "minecraft:sapling" ),
    BEDROCK( 7, "minecraft:bedrock" ),
    WATER( 8, "minecraft:flowing_water" ),
    STATIONARY_WATER( 9, "minecraft:water" ),
    LAVA( 10, "minecraft:lava" ),
    STATIONARY_LAVA( 11, "minecraft:flowing_lava" ),
    SAND( 12, "minecraft:sand" ),
    GRAVEL( 13, "minecraft:gravel" ),
    GOLD_ORE( 14, "minecraft:gold_ore" ),
    IRON_ORE( 15, "minecraft:iron_ore" ),
    COAL_ORE( 16, "minecraft:coal_ore" ),
    WOOD( 17, "minecraft:wood" ),
    LEAVES( 18, "minecraft:leaves" ),
    SPONGE( 19, "minecraft:sponge" ),
    GLASS( 20, "minecraft:glass" ),
    LAPIS_LAZULI_ORE( 21, "minecraft:lapis_ore" ),
    LAPIS_LAZULI_BLOCK( 22, "minecraft:lapis_block" ),
    DISPENSER( 23, "minecraft:dispenser" ),
    SANDSTONE( 24, "minecraft:sandstone" ),
    NOTE_BLOCK( 25, "minecraft:noteblock" ),
    POWERED_RAIL( 27, "minecraft:golden_rail" ),
    DETECTOR_RAIL( 28, "minecraft:detector_rail" ),
    STICKY_PISTON( 29, "minecraft:sticky_piston" ),
    COBWEB( 30, "minecraft:web" ),
    TALL_GRASS( 31, "minecraft:tallgrass" ),
    DEAD_BUSH( 32, "minecraft:deadbush" ),
    PISTON( 33, "minecraft:piston" ),
    PISTON_HEAD( 34, "minecraft:piston_head" ),
    WOOL( 35, "minecraft:wool" ),
    DANDELION( 37, "minecraft:yellow_flower" ),
    FLOWER( 38, "minecraft:red_flower" ),
    BROWN_MUSHROOM( 39, "minecraft:brown_mushroom" ),
    RED_MUSHROOM( 40, "minecraft:red_mushroom" ),
    BLOCK_OF_GOLD( 41, "minecraft:gold_block" ),
    BLOCK_OF_IRON( 42, "minecraft:iron_block" ),
    DOUBLE_STONE_SLAB( 43, "minecraft:double_stone_slab" ),
    STONE_SLAB( 44, "minecraft:stone_slab" ),
    BRICKS( 45, "minecraft:brick_block" ),
    TNT( 46, "minecraft:tnt" ),
    BOOKSHELF( 47, "minecraft:bookshelf" ),
    MOSS_STONE( 48, "minecraft:mossy_cobblestone" ),
    OBSIDIAN( 49, "minecraft:obsidian" ),
    TORCH( 50, "minecraft:torch" ),
    FIRE( 51, "minecraft:fire" ),
    MONSTER_SPAWNER( 52, "minecraft:mob_spawner" ),
    OAK_WOOD_STAIRS( 53, "minecraft:oak_stairs" ),
    CHEST( 54, "minecraft:chest" ),
    REDSTONE_WIRE( 55, "minecraft:redstone_wire" ),
    DIAMOND_ORE( 56, "minecraft:diamond_ore" ),
    BLOCK_OF_DIAMOND( 57, "minecraft:diamond_block" ),
    CRAFTING_TABLE( 58, "minecraft:crafting_table" ),
    CROPS( 59, "minecraft:wheat" ),
    FARMLAND( 60, "minecraft:farmland" ),
    FURNACE( 61, "minecraft:furnace" ),
    BURNING_FURNACE( 62, "minecraft:lit_furnace" ),
    LADDER( 65, "minecraft:ladder" ),
    RAIL( 66, "minecraft:rail" ),
    COBBLESTONE_STAIRS( 67, "minecraft:cobblestone_stairs" ),
    LEVER( 69, "minecraft:lever" ),
    STONE_PRESSURE_PLATE( 70, "minecraft:stone_pressure_plate" ),
    WOODEN_PRESSURE_PLATE( 72, "minecraft:wooden_pressure_plate" ),
    REDSTONE_ORE( 73, "minecraft:redstone_ore" ),
    GLOWING_REDSTONE_ORE( 74, "minecraft:lit_redstone_ore" ),
    REDSTONE_TORCH_INACTIVE( 75, "minecraft:unlit_redstone_torch" ),
    REDSTONE_TORCH_ACTIVE( 76, "minecraft:redstone_torch" ),
    STONE_BUTTON( 77, "minecraft:stone_button" ),
    TOP_SNOW( 78, "minecraft:snow_layer" ),
    ICE( 79, "minecraft:ice" ),
    SNOW( 80, "minecraft:snow" ),
    CACTUS( 81, "minecraft:cactus" ),
    CLAY( 82, "minecraft:clay" ),
    FENCE( 85, "minecraft:fence" ),
    PUMPKIN( 86, "minecraft:pumpkin" ),
    NETHERRACK( 87, "minecraft:netherrack" ),
    SOUL_SAND( 88, "minecraft:soul_sand" ),
    GLOWSTONE( 89, "minecraft:glowstone" ),
    PORTAL( 90, "minecraft:portal" ),
    JACK_O_LANTERN( 91, "minecraft:lit_pumpkin" ),
    REDSTONE_REPEATER_INACTIVE( 93, "minecraft:unpowered_repeater" ),
    REDSTONE_REPEATER_ACTIVE( 94, "minecraft:powered_repeater" ),
    INVISIBLE_BEDROCK( 95, "minecraft:stained_glass" ),
    TRAPDOOR( 96, "minecraft:trapdoor" ),
    MONSTER_EGG( 97, "minecraft:monster_egg" ),
    STONE_BRICK( 98, "minecraft:stone_brick" ),
    BROWN_MUSHROOM_BLOCK( 99, "minecraft:brown_mushroom_block" ),
    RED_MUSHROOM_BLOCK( 100, "minecraft:red_mushroom_block" ),
    IRON_BARS( 101, "minecraft:iron_bars" ),
    GLASS_PANE( 102, "minecraft:glass_pane" ),
    MELON_BLOCK( 103, "minecraft:melon_block" ),
    PUMPKIN_STEM( 104, "minecraft:pumpkin_stem" ),
    MELON_STEM( 105, "minecraft:melon_stem" ),
    VINES( 106, "minecraft:vines" ),
    FENCE_GATE( 107, "minecraft:fence_gate" ),
    BRICK_STAIRS( 108, "minecraft:brick_stairs" ),
    STONE_BRICK_STAIRS( 109, "minecraft:stone_brick_stairs" ),
    MYCELIUM( 110, "minecraft:mycelium" ),
    LILY_PAD( 111, "minecraft:lily_pad" ),
    NETHER_BRICK_BLOCK( 112, "minecraft:nether_brick" ),
    NETHER_BRICK_FENCE( 113, "minecraft:nether_brick_fence" ),
    NETHER_BRICK_STAIRS( 114, "minecraft:nether_brick_stairs" ),
    ENCHANTMENT_TABLE( 116, "minecraft:enchantment_table" ),
    END_PORTAL( 119, "minecraft:end_portal" ),
    END_PORTAL_FRAME( 120, "minecraft:end_portal_frame" ),
    END_STONE( 121, "minecraft:end_stone" ),
    DRAGON_EGG( 122, "minecraft:dragon_egg" ),
    REDSTONE_LAMP_INACTIVE( 123, "minecraft:redstone_lamp" ),
    REDSTONE_LAMP_ACTIVE( 124, "minecraft:lit_redstone_lamp" ),
    DROPPER( 125, "minecraft:dropper" ),
    ACTIVATOR_RAIL( 126, "minecraft:activator_rail" ),
    COCOA( 127, "minecraft:cocoa" ),
    SANDSTONE_STAIRS( 128, "minecraft:sandstone_stairs" ),
    EMERALD_ORE( 129, "minecraft:emerald_ore" ),
    ENDER_CHEST( 130, "minecraft:ender_chest" ),
    TRIPWIRE_HOOK( 131, "minecraft:tripwire_hook" ),
    TRIPWIRE( 132, "minecraft:tripwire" ),
    BLOCK_OF_EMERALD( 133, "minecraft:block_of_emerald" ),
    SPRUCE_WOOD_STAIRS( 134, "minecraft:spruce_wood_stairs" ),
    BIRCH_WOOD_STAIRS( 135, "minecraft:birch_wood_stairs" ),
    JUNGLE_WOOD_STAIRS( 136, "minecraft:jungle_wood_stairs" ),
    BEACON( 138, "minecraft:beacon" ),
    COBBLESTONE_WALL( 139, "minecraft:cobblestone_wall" ),
    CARROTS( 141, "minecraft:carrots" ),
    WOODEN_BUTTON( 143, "minecraft:wooden_button" ),
    SKULL( 144, "minecraft:skull" ),
    ANVIL( 145, "minecraft:anvil" ),
    TRAPPED_CHEST( 146, "minecraft:trapped_chest" ),
    WEIGHTED_PRESSURE_PLATE_LIGHT( 147, "minecraft:light_weighted_pressure_plate" ),
    WEIGHTED_PRESSURE_PLATE_HEAVY( 148, "minecraft:heavy_weighted_pressure_plate" ),
    REDSTONE_COMPARATOR_UNPOWERED( 149, "minecraft:unpowered_comparator" ),
    REDSTONE_COMPARATOR_POWERED( 150, "minecraft:powered_comparator" ),
    DAYLIGHT_SENSOR( 151, "minecraft:daylight_detector" ),
    BLOCK_OF_REDSTONE( 152, "minecraft:redstone_block" ),
    NETHER_QUARTZ_ORE( 153, "minecraft:quartz_ore" ),
    BLOCK_OF_QUARTZ( 155, "minecraft:quartz_block" ),
    QUARTZ_STAIRS( 156, "minecraft:quartz_stairs" ),
    WOODEN_DOUBLE_SLAB( 157, "minecraft:wooden_double_slab" ),
    WOODEN_SLAB( 158, "minecraft:wooden_slab" ),
    STAINED_CLAY( 159, "minecraft:stained_hardened_clay" ),
    STAINED_GLASS_PANE( 160, "minecraft:stained_glass_pane" ),
    ACACIA_LEAVES( 161, "minecraft:acacia_leaves" ),
    ACACIA_WOOD( 162, "minecraft:acacia_wood" ),
    ACACIA_WOOD_STAIRS( 163, "minecraft:acacia_wood_stairs" ),
    DARK_OAK_WOOD_STAIRS( 164, "minecraft:dark_oak_wood_stairs" ),
    SLIME_BLOCK( 165, "minecraft:slime_block" ),
    IRON_TRAPDOOR( 167, "minecraft:iron_trapdoor" ),
    PRISMARINE( 168, "minecraft:prismarine" ),
    SEA_LANTERN( 169, "minecraft:sea_lantern" ),
    HAY_BALE( 170, "minecraft:hay_bale" ),
    CARPET( 171, "minecraft:carpet" ),
    HARDENED_CLAY( 172, "minecraft:hardened_clay" ),
    BLOCK_OF_COAL( 173, "minecraft:block_of_coal" ),
    PACKED_ICE( 174, "minecraft:packed_ice" ),
    SUNFLOWER( 175, "minecraft:sunflower" ),
    INVERTED_DAYLIGHT_SENSOR( 178, "minecraft:inverted_daylight_sensor" ),
    RED_SANDSTONE( 179, "minecraft:red_sandstone" ),
    RED_SANDSTONE_STAIRS( 180, "minecraft:red_sandstone_stairs" ),
    DOUBLE_RED_SANDSTONE_SLAB( 181, "minecraft:double_red_sandstone_slab" ),
    RED_SANDSTONE_SLAB( 182, "minecraft:red_sandstone_slab" ),
    SPRUCE_FENCE_GATE( 183, "minecraft:spruce_fence_gate" ),
    BIRCH_FENCE_GATE( 184, "minecraft:birch_fence_gate" ),
    JUNGLE_FENCE_GATE( 185, "minecraft:jungle_fence_gate" ),
    DARK_OAK_FENCE_GATE( 186, "minecraft:dark_oak_fence_gate" ),
    ACACIA_FENCE_GATE( 187, "minecraft:acacia_fence_gate" ),
    GRASS_PATH( 198, "minecraft:grass_path" ),
    CHORUS_FLOWER( 200, "minecraft:chorus_flower" ),
    PURPUR_BLOCK( 201, "minecraft:purpur_block" ),
    PURPUR_STAIRS( 203, "minecraft:purpur_stairs" ),
    END_BRICKS( 206, "minecraft:end_bricks" ),
    END_ROD( 208, "minecraft:end_rod" ),
    END_GATEWAY( 209, "minecraft:end_gateway" ),
    CHORUS_PLANT( 240, "minecraft:chorus_plant" ),
    STAINED_GLASS( 241, "minecraft:stained_glass" ),
    PODZOL( 243, "minecraft:podzol" ),
    BEETROOT_PLANT( 244, "minecraft:beetroots" ),
    STONECUTTER( 245, "minecraft:stonecutter" ),
    GLOWING_OBSIDIAN( 246, "minecraft:glowing_obsidian" ),
    NETHER_REACTOR_CORE( 247, "minecraft:nether_reactor_core" ),
    BLOCK_MOVED_BY_PISTON( 250, "minecraft:block_moved_by_piston" ),
    OBSERVER( 251, "minecraft:observer" ),
    RESERVED6( 255, "minecraft:reserved6" ),
    ALLOW( 210, "minecraft:allow" ),
    DENY( 211, "minecraft:deny" ),
    BORDER_BLOCK( 212, "minecraft:border_block" ),
    IRON_SHOVEL( 256, "minecraft:iron_shovel" ),
    IRON_PICKAXE( 257, "minecraft:iron_pickaxe" ),
    IRON_AXE( 258, "minecraft:iron_axe" ),
    FLINT_AND_STEEL( 259, "minecraft:flint_and_steel" ),
    APPLE( 260, "minecraft:apple" ),
    BOW( 261, "minecraft:bow" ),
    ARROW( 262, "minecraft:arrow" ),
    COAL( 263, "minecraft:coal" ),
    DIAMOND( 264, "minecraft:diamond" ),
    IRON_INGOT( 265, "minecraft:iron_ingot" ),
    GOLD_INGOT( 266, "minecraft:gold_ingot" ),
    IRON_SWORD( 267, "minecraft:iron_sword" ),
    WOODEN_SWORD( 268, "minecraft:wooden_sword" ),
    WOODEN_SHOVEL( 269, "minecraft:wooden_shovel" ),
    WOODEN_PICKAXE( 270, "minecraft:wooden_pickaxe" ),
    WOODEN_AXE( 271, "minecraft:wooden_axe" ),
    STONE_SWORD( 272, "minecraft:stone_sword" ),
    STONE_SHOVEL( 273, "minecraft:stone_shovel" ),
    STONE_PICKAXE( 274, "minecraft:stone_pickaxe" ),
    STONE_AXE( 275, "minecraft:stone_axe" ),
    DIAMOND_SWORD( 276, "minecraft:diamond_sword" ),
    DIAMOND_SHOVEL( 277, "minecraft:diamond_shovel" ),
    DIAMOND_PICKAXE( 278, "minecraft:diamond_pickaxe" ),
    DIAMOND_AXE( 279, "minecraft:diamond_axe" ),
    STICK( 280, "minecraft:stick" ),
    BOWL( 281, "minecraft:bowl" ),
    MUSHROOM_STEW( 282, "minecraft:mushroom_stew" ),
    GOLDEN_SWORD( 283, "minecraft:golden_sword" ),
    GOLDEN_SHOVEL( 284, "minecraft:golden_shovel" ),
    GOLDEN_PICKAXE( 285, "minecraft:golden_pickaxe" ),
    GOLDEN_AXE( 286, "minecraft:golden_axe" ),
    STRING( 287, "minecraft:string" ),
    FEATHER( 288, "minecraft:feather" ),
    GUNPOWDER( 289, "minecraft:gunpowder" ),
    WOODEN_HOE( 290, "minecraft:wooden_hoe" ),
    STONE_HOE( 291, "minecraft:stone_hoe" ),
    IRON_HOE( 292, "minecraft:iron_hoe" ),
    DIAMOND_HOE( 293, "minecraft:diamond_hoe" ),
    GOLDEN_HOE( 294, "minecraft:golden_hoe" ),
    SEEDS( 295, "minecraft:seeds" ),
    WHEAT( 296, "minecraft:wheat" ),
    BREAD( 297, "minecraft:bread" ),
    LEATHER_CAP( 298, "minecraft:leather_cap" ),
    LEATHER_TUNIC( 299, "minecraft:leather_tunic" ),
    LEATHER_PANTS( 300, "minecraft:leather_pants" ),
    LEATHER_BOOTS( 301, "minecraft:leather_boots" ),
    CHAIN_HELMET( 302, "minecraft:chain_helmet" ),
    CHAIN_CHESTPLATE( 303, "minecraft:chain_chestplate" ),
    CHAIN_LEGGINGS( 304, "minecraft:chain_leggings" ),
    CHAIN_BOOTS( 305, "minecraft:chain_boots" ),
    IRON_HELMET( 306, "minecraft:iron_helmet" ),
    IRON_CHESTPLATE( 307, "minecraft:iron_chestplate" ),
    IRON_LEGGINGS( 308, "minecraft:iron_leggings" ),
    IRON_BOOTS( 309, "minecraft:iron_boots" ),
    DIAMOND_HELMET( 310, "minecraft:diamond_helmet" ),
    DIAMOND_CHESTPLATE( 311, "minecraft:diamond_chestplate" ),
    DIAMOND_LEGGINGS( 312, "minecraft:diamond_leggings" ),
    DIAMOND_BOOTS( 313, "minecraft:diamond_boots" ),
    GOLDEN_HELMET( 314, "minecraft:golden_helmet" ),
    GOLDEN_CHESTPLATE( 315, "minecraft:golden_chestplate" ),
    GOLDEN_LEGGINGS( 316, "minecraft:golden_leggings" ),
    GOLDEN_BOOTS( 317, "minecraft:golden_boots" ),
    FLINT( 318, "minecraft:flint" ),
    RAW_PORKCHOP( 319, "minecraft:raw_porkchop" ),
    COOKED_PORKCHOP( 320, "minecraft:cooked_porkchop" ),
    PAINTING( 321, "minecraft:painting" ),
    GOLDEN_APPLE( 322, "minecraft:golden_apple" ),
    SIGN( 323, "minecraft:sign" ),
    WOODEN_DOOR( 324, "minecraft:wooden_door" ),
    BUCKET( 325, "minecraft:bucket" ),
    MINECART( 328, "minecraft:minecart" ),
    SADDLE( 329, "minecraft:saddle" ),
    IRON_DOOR( 330, "minecraft:iron_door" ),
    REDSTONE( 331, "minecraft:redstone" ),
    SNOWBALL( 332, "minecraft:snowball" ),
    BOAT( 333, "minecraft:boat" ),
    LEATHER( 334, "minecraft:leather" ),
    BRICK( 336, "minecraft:brick" ),
    CLAY_BALL( 337, "minecraft:clay_ball" ),
    SUGAR_CANE( 338, "minecraft:reeds" ),
    PAPER( 339, "minecraft:paper" ),
    BOOK( 340, "minecraft:book" ),
    SLIMEBALL( 341, "minecraft:slimeball" ),
    MINECART_WITH_CHEST( 342, "minecraft:minecart_with_chest" ),
    EGG( 344, "minecraft:egg" ),
    COMPASS( 345, "minecraft:compass" ),
    FISHING_ROD( 346, "minecraft:fishing_rod" ),
    CLOCK( 347, "minecraft:clock" ),
    GLOWSTONE_DUST( 348, "minecraft:glowstone_dust" ),
    RAW_FISH( 349, "minecraft:raw_fish" ),
    COOKED_FISH( 350, "minecraft:cooked_fish" ),
    DYE( 351, "minecraft:dye" ),
    BONE( 352, "minecraft:bone" ),
    SUGAR( 353, "minecraft:sugar" ),
    CAKE( 354, "minecraft:cake" ),
    BED( 355, "minecraft:bed" ),
    REDSTONE_REPEATER( 356, "minecraft:redstone_repeater" ),
    COOKIE( 357, "minecraft:cookie" ),
    FILLED_MAP( 358, "minecraft:filled_map" ),
    SHEARS( 359, "minecraft:shears" ),
    MELON( 360, "minecraft:melon" ),
    PUMPKIN_SEEDS( 361, "minecraft:pumpkin_seeds" ),
    MELON_SEEDS( 362, "minecraft:melon_seeds" ),
    RAW_BEEF( 363, "minecraft:raw_beef" ),
    STEAK( 364, "minecraft:steak" ),
    RAW_CHICKEN( 365, "minecraft:raw_chicken" ),
    COOKED_CHICKEN( 366, "minecraft:cooked_chicken" ),
    ROTTEN_FLESH( 367, "minecraft:rotten_flesh" ),
    ENDER_PEARL( 368, "minecraft:ender_pearl" ),
    BLAZE_ROD( 369, "minecraft:blaze_rod" ),
    GHAST_TEAR( 370, "minecraft:ghast_tear" ),
    GOLD_NUGGET( 371, "minecraft:gold_nugget" ),
    NETHER_WART( 372, "minecraft:nether_wart" ),
    POTION( 373, "minecraft:potion" ),
    GLASS_BOTTLE( 374, "minecraft:glass_bottle" ),
    SPIDER_EYE( 375, "minecraft:spider_eye" ),
    FERMENTED_SPIDER_EYE( 376, "minecraft:fermented_spider_eye" ),
    BLAZE_POWDER( 377, "minecraft:blaze_powder" ),
    MAGMA_CREAM( 378, "minecraft:magma_cream" ),
    BREWING_STAND( 379, "minecraft:brewing_stand" ),
    CAULDRON( 380, "minecraft:cauldron" ),
    EYE_OF_ENDER( 381, "minecraft:eye_of_ender" ),
    GLISTERING_MELON( 382, "minecraft:glistering_melon" ),
    SPAWN_EGG( 383, "minecraft:spawn_egg" ),
    EXPERIENCE_BOTTLE( 384, "minecraft:experience_bottle" ),
    FIRE_CHARGE( 385, "minecraft:fire_charge" ),
    EMERALD( 388, "minecraft:emerald" ),
    ITEM_FRAME( 389, "minecraft:item_frame" ),
    FLOWER_POT( 390, "minecraft:flower_pot" ),
    CARROT( 391, "minecraft:carrot" ),
    POTATO( 392, "minecraft:potato" ),
    BAKED_POTATO( 393, "minecraft:baked_potato" ),
    POISONOUS_POTATO( 394, "minecraft:poisonous_potato" ),
    MAP( 395, "minecraft:map" ),
    GOLDEN_CARROT( 396, "minecraft:golden_carrot" ),
    MOB_HEAD( 397, "minecraft:mob_head" ),
    CARROT_ON_A_STICK( 398, "minecraft:carrot_on_a_stick" ),
    NETHER_STAR( 399, "minecraft:nether_star" ),
    PUMPKIN_PIE( 400, "minecraft:pumpkin_pie" ),
    ENCHANTED_BOOK( 403, "minecraft:enchanted_book" ),
    COMPARATOR( 404, "minecraft:comparator" ),
    NETHER_BRICK( 405, "minecraft:netherbrick" ),
    NETHER_QUARTZ( 406, "minecraft:nether_quartz" ),
    MINECART_WITH_TNT( 407, "minecraft:minecart_with_tnt" ),
    MINECART_WITH_HOPPER( 408, "minecraft:minecart_with_hopper" ),
    PRISMARINE_SHARD( 409, "minecraft:prismarine_shard" ),
    HOPPER( 410, "minecraft:hopper" ),
    RAW_RABBIT( 411, "minecraft:raw_rabbit" ),
    COOKED_RABBIT( 412, "minecraft:cooked_rabbit" ),
    RABBIT_STEW( 413, "minecraft:rabbit_stew" ),
    RABBIT_FOOT( 414, "minecraft:rabbit_foot" ),
    RABBIT_HIDE( 415, "minecraft:rabbit_hide" ),
    LEATHER_HORSE_ARMOR( 416, "minecraft:leather_horse_armor" ),
    IRON_HORSE_ARMOR( 417, "minecraft:iron_horse_armor" ),
    GOLDEN_HORSE_ARMOR( 418, "minecraft:golden_horse_armor" ),
    DIAMOND_HORSE_ARMOR( 419, "minecraft:diamond_horse_armor" ),
    LEAD( 420, "minecraft:lead" ),
    NAME_TAG( 421, "minecraft:name_tag" ),
    PRISMARINE_CRYSTALS( 422, "minecraft:prismarine_crystals" ),
    MUTTON( 423, "minecraft:mutton" ),
    COOKED_MUTTON( 424, "minecraft:cooked_mutton" ),
    END_CRYSTAL( 426, "minecraft:end_crystal" ),
    SPRUCE_DOOR( 427, "minecraft:spruce_door" ),
    BIRCH_DOOR( 428, "minecraft:birch_door" ),
    JUNGLE_DOOR( 429, "minecraft:jungle_door" ),
    ACACIA_DOOR( 430, "minecraft:acacia_door" ),
    DARK_OAK_DOOR( 431, "minecraft:dark_oak_door" ),
    CHORUS_FRUIT( 432, "minecraft:chorus_fruit" ),
    POPPED_CHORUS_FRUIT( 433, "minecraft:popped_chorus_fruit" ),
    DRAGON_BREATH( 437, "minecraft:dragon_breath" ),
    SPLASH_POTION( 438, "minecraft:splash_potion" ),
    LINGERING_POTION( 441, "minecraft:lingering_potion" ),
    ELYTRA( 444, "minecraft:elytra" ),
    SHULKER_SHELL( 445, "minecraft:shulker_shell" ),
    BEETROOT( 457, "minecraft:beetroot" ),
    BEETROOT_SEEDS( 458, "minecraft:beetroot_seeds" ),
    BEETROOT_SOUP( 459, "minecraft:beetroot_soup" ),
    RAW_SALMON( 460, "minecraft:raw_salmon" ),
    CLOWNFISH( 461, "minecraft:clownfish" ),
    PUFFERFISH( 462, "minecraft:pufferfish" ),
    COOKED_SALMON( 463, "minecraft:cooked_salmon" ),
    ENCHANTED_GOLDEN_APPLE( 466, "minecraft:enchanted_golden_apple" ),
    CHALKBOARD( 454, "minecraft:chalkboard" ),
    PORTFOLIO( 456, "minecraft:portfolio" ),
    CAMERA( 498, "minecraft:camera" );

    private static final Logger LOGGER = LoggerFactory.getLogger( MaterialMagicNumbers.class );

    @Getter
    private final int oldId;
    private final String newId;

    MaterialMagicNumbers( int oldID, String newId ) {
        this.oldId = oldID;
        this.newId = newId;
    }
    // CHECKSTYLE:ON

    public static MaterialMagicNumbers valueOfWithId( String newId ) {
        // TODO: Build a tool to generate a switch table
        String intern = newId.intern();
        for ( MaterialMagicNumbers materialMagicNumbers : values() ) {
            if ( materialMagicNumbers.newId.intern() == intern ) {
               return materialMagicNumbers;
            }
        }

        LOGGER.warn( "Unknown item id: " + newId );
        return null;
    }

    public static MaterialMagicNumbers valueOfWithId( int oldId ) {
        // TODO: Build a tool to generate a switch table
        for ( MaterialMagicNumbers materialMagicNumbers : values() ) {
            if ( materialMagicNumbers.oldId == oldId ) {
                return materialMagicNumbers;
            }
        }

        LOGGER.warn( "Unknown item id: " + oldId );
        return null;
    }

}
